### ISSUE TITLE
apiInstance.queryScalarData does not support Percentile as Aggregator

### ISSUE THREAD

**Issue by jeffhorus** [DataDog/datadog-api-client-typescript#1018]
**Describe the bug**
Query Scalar Data Request does not support Percentile as Aggregator, when the Scalar API supports it

***It is supported in Datadog Dashboard***
<img width="1410" alt="Screen Shot 2023-02-10 at 10 23 53" src="https://user-images.githubusercontent.com/7077135/217992785-d51012d2-df75-4aa8-9eea-470504621836.png">

***It is supported by direct call to Scalar API***
<img width="1030" alt="Screen Shot 2023-02-10 at 10 25 23" src="https://user-images.githubusercontent.com/7077135/217993017-07b8c69a-c9e9-465c-af9e-a72ea3d6a7c6.png">

***But It is not supported using Library, because the `v2.MetricsApiQueryScalarDataRequest` is enumerating the aggregator but without `percentile` as options***
https://github.com/DataDog/datadog-api-client-typescript/blob/51d6c508c9c6884ff2671041040c7dd0b7985bb7/packages/datadog-api-client-v2/models/MetricsAggregator.ts#L13-L24

**To Reproduce**
This will be compilation error, because the aggregator can only be `avg, max, min, sum, last`
```
const params: v2.MetricsApiQueryScalarDataRequest = {
  body: {
    data: {
      attributes: {
        formulas: [
          {
            formula: "a",
            limit: {
              count: 10,
              order: "desc",
            },
          },
        ],
        from: 1671612804000,
        queries: [
          {
            aggregator: "percentile",
            dataSource: "metrics",
            query: "p99:system.cpu.user{*}",
            name: "a",
          },
        ],
        to: 1671620004000,
      },
      type: "scalar_request",
    },
  },
};
```

**Expected behavior**
Percentile should be accepted

**Screenshots**
Screenshots added above

**Environment and Versions (please complete the following information):**
- version for this project in use: "@datadog/datadog-api-client": "1.9.0",
- services, libraries, languages and tools list and versions: typescript

**Additional context**
n.a.

**Comment by therve** [comment]
Should be fixed in #1029, thanks!
