### ISSUE TITLE
Request returns empty 429

### ISSUE THREAD

**Issue by reut-wild-moose** [DataDog/datadog-api-client-typescript#1511]
There seems to be an internal Datadog bug
We are seeing the log messages: `Got error deserializing error: Error: missing required property 'errors'` coming from Datadog SDK, it seems to happen when our api calls returns 429

The error code body returned is empty:

```
HTTP-Code: 429
Message: ""
```

it seems like an internal issue where DD expects to have `errors` property for this error but doesn't

**Comment by skarimo** [comment]
Hello, thanks for the report. You are correct, this occurs when the error response differs from the anticipated response, in this case missing `errors`. 

However, we ensure a proper `APIException` is still thrown, for example: https://github.com/DataDog/datadog-api-client-typescript/blob/master/packages/datadog-api-client-v1/apis/DashboardsApi.ts#L681-L685

I think this log is a bit noisy and we will look into removing it or downgrading it to debug instead.
