### ISSUE TITLE
Error LogsApi

### ISSUE THREAD

**Issue by lucasyarid** [DataDog/datadog-api-client-typescript#353]
**Describe the bug**
I'm trying to dispatch a single log to DataDog and decided to use this official lib instead of doing it via HTTP.

Following the exact example given [here](https://docs.datadoghq.com/api/latest/logs/#send-logs) I'm getting the current error:
```sh
TypeError: missing required attribute 'code' on 'HTTPLogError' object
    at Function.HTTPLogError.deserialize (.../node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/models/HTTPLogError.js:26:19)
```

**To Reproduce**
Follow exactly as described on [DataDog website](https://docs.datadoghq.com/api/latest/logs/#send-logs)

**Expected behavior**
Event being dispatch, or at least a readable error.

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - ^1.0.0-beta.5
  - node v14.18.0

**Additional context**
Seems this package is in it's early development, shall I use something else?

Thank you

**Comment by lucasyarid** [comment]
Just saw https://github.com/DataDog/datadog-api-client-typescript/issues/313 and gonna try the proposed solution

**Comment by therve** [comment]
Hi,

There is a window where our examples reflect master code and the release hasn't been done yet. If you remove the `contentEncoding` option it should work just fine. Sorry for the trouble.

**Comment by lucasyarid** [comment]
Indeed it worked.
Thanks for the quick answer

**Comment by therve** [comment]
It should be fine now with beta 6.
