### ISSUE TITLE
Uncaught Exceptions When Initializing Client

### ISSUE THREAD

**Issue by danwize** [DataDog/datadog-api-client-typescript#462]
Uncaught exceptions in DatadogLibrary when trying to initialize api clients.

Label the issue properly.
- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
1. Create a new react app:  npx create-react-app system-status-display --template typescript
2. Install the data dog client: npm install @datadog/datadog-api-client
3. Create a Datadog.ts file like this:
`import { v1 } from "@datadog/datadog-api-client";
import { ConfigurationParameters } from "@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/configuration";
const configurationOptions:ConfigurationParameters = {
    //@ts-ignore
    debug: true,
    httpConfig:{
        compress: false
    }
}
const configurtion = v1.createConfiguration(configurationOptions);
const apiInstance = new v1.SyntheticsApi(configurtion);
export const getSyntheticTests = async ()=>{
    let tests = await apiInstance.listTests();
    return tests.tests;
}`
3. Call the getSyntheticTestsMethod from App.tsx.  Add this code inside the App component
`const getStuffFromDataDog = useEffect(()=>{
    let serviceGroups:ServiceGroup[] = [];
    let apiServiceGroup: ServiceGroup = {
      name: "Apis",
      services: []
    };
    let datadogSynthetics = getSyntheticTests();
    //set up x api stuff
    let belleXApiService: Service = {
      name: "X API",
      status:ServiceStatus.Good
    };
  });`
4. When the Datadog client is initalized, I see this exception in the javascript console:

> Uncaught ReferenceError: process is not defined
    at Object../node_modules/@datadog/datadog-api-client/dist/userAgent.js (userAgent.ts:4)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/http/http.js (http.ts:1)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../node_modules/@datadog/datadog-api-client/dist/packages/datadog-api-client-v1/index.js (index.ts:1)
    at Object.options.factory (react refresh:6)

**Expected behavior**
DataDog api client should initialize and return the list of synthetic tests.

**Environment and Versions (please complete the following information):**
node js project in visual studio code on windows 10.  Chrome Browser:
  - react
  - typescript
  - @datadog/datadog-api-client": "^1.0.0-beta.6

[system-status-display.zip](https://github.com/DataDog/datadog-api-client-typescript/files/7831656/system-status-display.zip)

**Comment by danwize** [comment]
Does Datadog expose their open api json file so I can try generating a client?

**Comment by therve** [comment]
Hi, for now this is a node only project, so it won't work in the browser as you noticed. The spec files are in https://github.com/DataDog/datadog-api-client-typescript/tree/master/.generator/schemas.

**Comment by therve** [comment]
Should be fixed by #899
