### ISSUE TITLE
Postmortems return as `undefined` with `.getIncident()`

### ISSUE THREAD

**Issue by Apollorion** [DataDog/datadog-api-client-typescript#501]
**Describe the bug**
When using `.getIncident()` the `data.data.relationships.postmortem` and `data.data.attributes.postmortemId` attributes are `undefined` even when a postmortem is attached to the incident.

I've also opened a support request for this `653993`

**To Reproduce**

1. Create an incident in datadog, resolve it, and then generate a postmortem document to it.
2. run the following code, assuming the incident you created was `incident-29`.

```
import { v2 } from "@datadog/datadog-api-client";

const configuration = v2.createConfiguration();
const apiInstance = new v2.IncidentsApi(configuration);
const params: v2.IncidentsApiGetIncidentRequest = {
    incidentId: 29,
};

apiInstance
.getIncident(params)
.then(async (data: any) => {
	console.log(data.data.relationships);
	console.log(data.data.attributes);
});
```

**Expected behavior**
I get the postmortem response as defined [here](https://docs.datadoghq.com/api/latest/incidents/#get-the-details-of-an-incident).

**Environment and Versions (please complete the following information):**
`"@datadog/datadog-api-client": "^1.0.0-beta.6"`
Using node docker: `node:lts-buster`

**Comment by Apollorion** [comment]
This appears to be an issue with the underlying `GET https://api.datadoghq.com/api/v2/incidents/{incident_id}` response.

I ran the postman project [here](https://docs.datadoghq.com/api/latest/) to see if I could get around this issue by not using the library, and it doesn't appear that any of the postmortem attributes are returned from the API, full stop.

Hoping Datadog can turn around on fixing the endpoint, [since its documented in the response](https://docs.datadoghq.com/api/latest/incidents/#get-the-details-of-an-incident) that postmortemId is an attribute of this call.

**Comment by therve** [comment]
Right, `postmortems` have been replaced by `attachments`, we're working with the Incident team to sync the clients. Sorry for the troubles.

**Comment by Apollorion** [comment]
> Right, `postmortems` have been replaced by `attachments`, we're working with the Incident team to sync the clients. Sorry for the troubles.

Hey @therve thanks! Is there a way to differentiate a postmortem attachment from `Other Docs` in the ui? The `attachments` gives me an ID, but I don't see an endpoint to get more information about that attachment. I am basically just trying to be notified when a postmortem document has been generated for an incident.

**Comment by therve** [comment]
I think the easiest way is to pass `?include=attachments` in the query arguments, which should add your postmortems to the `included` payload with `attachment_type` equal to `postmortem`.

**Comment by Apollorion** [comment]
> I think the easiest way is to pass `?include=attachments` in the query arguments, which should add your postmortems to the `included` payload with `attachment_type` equal to `postmortem`.

Perfect, this is working exactly as I needed! I did have to use the direct API instead of this library though. `include` only allows an array of `["users"]` with this library. Ill let you guys over at datadog figure out what you wanna do with this issue. Im okay to close it if you guys are as what I needed this for is no longer required.

**Comment by therve** [comment]
Thank you, we'll keep the issue opened until we offer the feature via the SDK.
