### ISSUE TITLE
FetchError: request to https://api.datadoghq.com/api/v1/series failed

### ISSUE THREAD

**Issue by iblessedi** [DataDog/datadog-api-client-typescript#674]
Hello! I am trying to send custom metrics to DataDog from the Google Cloud function. The code is like:

```
const params = {
	body: {
		series: [
			{
				metric: name,
				type: "count",
				points: [ [ new Date().getTime() / 1000, 1 ] ],
				tags: [
					`env:${process.env.NODE_ENV}`
				],
			},
		],
	},
};

apiInstance
	.submitMetrics(params)
	.catch((error) => logger.warn(`Cannot post custom ${name} to DataDog`, error));
```

The problem is that I receive many errors like 
`FetchError: request to https://api.datadoghq.com/api/v1/series failed, reason: connect ETIMEDOUT 3.233.147.157:443`

and I see many such errors! So, some of the requests are successful and some cause an error. Why do I see such an issue? Thanks.

**Comment by therve** [comment]
Hi,

It seems very unlikely to be a bug in the client. I don't think we've had an incident with metric intake either. So it's probably something to do with your environment? I don't know about Google Cloud functions, do you need specific network setup? Do you have something reproducible? Thanks.

**Comment by therve** [comment]
Closing it for now, feels free to reopen with more information. Thank you.
