### ISSUE TITLE
NPM and yarn installs don't work - Module '"@datadog/datadog-api-client"' has no exported member 'client' | Property 'RUMApi' does not exist on type 'typeof import

### ISSUE THREAD

**Issue by harper-amyris** [DataDog/datadog-api-client-typescript#712]
**Describe the bug**

I'm getting error `Property 'RUMApi' does not exist on type 'typeof import` when I try to follow the documentation, it also happens with client. I tried installed via both NPM and yarn but it's the same problem

**To Reproduce**

It's an issue in 2 different cases:

Case 1 (clientConfiguration):

```
import { client, v2 } from "@datadog/datadog-api-client";

const configuration = client.createConfiguration();
const apiInstance = new v2.RUMApi(configuration);

apiInstance
  .listRUMEvents()
  .then((data: v2.RUMEventsResponse) => {
    console.log(
      "API called successfully. Returned data: " + JSON.stringify(data)
    );
  })
  .catch((error: any) => console.error(error));
```

I get both errors: Module '"@datadog/datadog-api-client"' has no exported member 'client' AND Property 'RUMApi' does not exist on type 'typeof import

Case 2:

```
import { v2 } from "@datadog/datadog-api-client";

// API creds
const configurationOpts = {
  authMethods: {
    apiKeyAuth: "API_KEY",
    appKeyAuth: "APP_KEY"
  },
};

// set up config
const configuration = v2.createConfiguration(configurationOpts);
const apiInstance = new v2.RUMApi(configuration);

apiInstance
  .listRUMEvents()
  .then((data: v2.RUMEventsResponse) => {
    console.log(
      "API called successfully. Returned data: " + JSON.stringify(data)
    );
  })
  .catch((error: any) => console.error(error));
```

I only get  Property 'RUMApi' does not exist on type 'typeof import

**Expected behavior**
I get no errors

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:

windows 
node v14.6.0
yarn 1.22.18

**Additional context**

how do you fix this?

**Comment by therve** [comment]
Hello,

The examples reflect master and we just refactored the modules. I'm preparing the release to make the changes available. Sorry for the troubles.

**Comment by therve** [comment]
Just released 1.0.0., thanks.

**Comment by harper-amyris** [comment]
@therve this issue needs to be reopened...now `v1.createCongifuration()` and `v2.createConfiguration(configurationOpts);` have stopped working. 

Please advise when this can be addressed. Thank you.

**Comment by harper-amyris** [comment]
Quick update but I want to confirm that `v1` and `v2` no longer have `createConfiguration` as a method - is that correct?

Because I got this to work:

```
import { client, v1 } from '@datadog/datadog-api-client';

console.log('running a datadog thing')

// API creds
const configurationOpts = {
  authMethods: {
    apiKeyAuth: "API_KEY_GOES_HERE",
    appKeyAuth: "APP_KEY_GOES_HERE"
  },
};

// set up config
const configuration = client.createConfiguration(configurationOpts);
```

And this successfully authenticates the API.

**Comment by therve** [comment]
That's correct we made that change before the first 1.0 release version. There were still a few places with the old API in the README, I fixed those now. Thanks.
