### ISSUE TITLE
alert_type should be status.

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [DataDog/datadog-api-client-typescript#753]
**Describe the bug**
The documentation for creating an Event specifies that we should set alert_type (in typescript alertType) to error, status, info, etc.  However, this doesn't show up anywhere in the Event Explorer.  Instead, if you add a property called status, then that's what shows up in the Event explorer.  However, status isn't part of the Typescript definition file, so it registers as an error unless set using event["status"]  notation.  Both the documentation and the Typescript definitions should be updated.  Or maybe the actual createEvent api at DataDog needs to be updated?

**To Reproduce**

1. Goto the Event explorer
2. Post an event to the https://api.datadoghq.com/api/v1/events endpoint using alert_type and see it get ignored
3. Post an event to the https://api.datadoghq.com/api/v1/events endpoint using the undocumented and untyped status and see it show up.

**Expected behavior**
I would expect the alert_type to appear somewhere, and barring that, I would expect the typescript definition files to include status instead of alert_type and I would expect the documentation to tell us to send status instead of alert_type

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:

- version for this project in use.
- Currently using "@datadog/datadog-api-client": "1.0.0" npm package along with the v1 Endpoints as described in the Documentation for Typescript.
- services, libraries, languages and tools list and versions.
- Typescript
- NodeJS

**Comment by therve** [comment]
Hi,

I just tested against our test org and alertTType properly got reflected to status in the UI: 
![image](https://user-images.githubusercontent.com/159137/177949776-d90a5710-913b-417a-9132-99fc1b1bedc0.png) and I can filter it using the status facet.

That said, it may depend on account configuration, as we're rolling out v2 of the event API. Can you contact support so we investigate against your account? Thanks.

**Comment by therve** [comment]
Closing for now, feel free to reopen with more information.
