### ISSUE TITLE
criticalRecovery and warningRecovery always fail for `createMonitor`

### ISSUE THREAD

**Issue by paco-sparta** [DataDog/datadog-api-client-typescript#754]
**Describe the bug**
This is a problem with the backend, but I cannot find the right repo.

I have a project with the following monitor, exported directly from the UI:

```ts
  type: MonitorType.QUERY_ALERT,
  query: `avg(last_1d):anomalies(max:system.cpu.user{env:${enviro},service:${monitor.service}} by {host}, 'agile', 2, direction='both', interval=300, alert_window='last_1h', count_default_zero='true', seasonality='weekly') > 0.5`,
  message: `[${monitor.service}] CPU usage is too high.`,
  options: {
    thresholds: {
      critical: 0.5,
      criticalRecovery: 0.25,
      warning: 0.2,
      warningRecovery: 0.1,
    },
```

For this use case the API `monitorsApi.createMonitor` always returns:

```ts
"error": {
      "code": 400,
      "body": {
        "errors": [
          "alert and alert recovery criteria are such that the monitor can be simultaneously in alert and alert recovery states"
        ]
      }
    }
```

No matter what values I put in criticalRecovery and warningRecovery both always error.

**To Reproduce**

1. Using the API
2. Create a QUERY_ALERT monitor with criticalRecovery and warningRecovery
3. Request createMonitor

**Expected behavior**
These values should be accepted, as they match the website's.

**Environment and Versions (please complete the following information):**
`"@datadog/datadog-api-client": "^1.0.0",`

**Additional context**
This is a backend problem, the error happens after the request goes through. I'd be happy to forward it to the corresponding repo.

**Comment by therve** [comment]
Hi,

Can you submit a ticket with support please: https://www.datadoghq.com/support/. There is no GIthub repo for backend. Thanks.

**Comment by paco-sparta** [comment]
Is there a way not to go through support escalations for what is a technical glitch you can ask about in an internal channel?

**Comment by paco-sparta** [comment]
The solution was to change `triggerWindow` and `recoveryWindow` so that trigger <= recovery
