### ISSUE TITLE
How to change the Datadog host?

### ISSUE THREAD

**Issue by gitSambhal** [DataDog/datadog-api-client-typescript#928]
Is there any way to change the host name in Datadog? I tried giving DD_HOST and DD_HOSTNAME in .env file but it didn't work.
I am using [pino-datadog-transport](https://github.com/theogravity/pino-datadog-transport/) in NestJS.
Currently it is taking the machine name as host.

![image](https://user-images.githubusercontent.com/15196655/203953878-3bf5f770-9071-427a-bfac-3a2abd418051.png)

Ref: https://github.com/theogravity/pino-datadog-transport/issues/11

**Comment by therve** [comment]
Presumably you're mentioning logs and https://docs.datadoghq.com/api/latest/logs/#send-logs? In that case you need to set the `hostname` field of the payload.

**Comment by therve** [comment]
Closing for now, feel free to reopen if that doesn't work.
